### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by MhdHejazi** [dehesa/CodableCSV#10]
After decoding the CSV file I noticed that many objects created by the decoder are still in memory. After a quick look, it looks like there is a retain cycle here that causes a memory leak:
```
DecodingRecordOrdered -> decoder -> chain -> state -> DecodingRecordOrdered
```
I think one of those references needs to be weak to break this cycle.

**Comment by dehesa** [comment]
Hi @MhdHejazi,

Thanks for bringing this to my attention. I will try to replicate and to fix it. I will let you know once I do.

**Comment by dehesa** [comment]
Hey again @MhdHejazi,

I believe I have resolved the memory leak problems with the new release. It will help me if you could take a look at it and run the new release on your data.

Thank you for reporting.

**Comment by MhdHejazi** [comment]
I actually had to replace the library (see #11). But I tested the new version now and can confirm the issue is resolved.

**Comment by dehesa** [comment]
Great, thank you @MhdHejazi
