### ISSUE TITLE
Encoding a struct with a nil value results in an infinite loop.

### ISSUE THREAD

**Issue by roydaw** [dehesa/CodableCSV#17]
## Describe the bug
Encoding a struct with a nil value results in an infinite loop.

## To Reproduce
```
import Foundation
import CodableCSV

struct Employee: Encodable {
    let id: Int
    let name: String
    let supervisorId: Int?
    
    enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Employee ID"
        case name = "Name"
        case supervisorId = "Supervisor ID"
    }
}

let oneEmployee = Employee(id: 1, name: "Roy", supervisorId: nil)

let encoder = CSVEncoder {
    $0.headers = Employee.CodingKeys.allCases.map(\.rawValue)
}
let result = try! encoder.encode([oneEmployee], into: String.self)

print(result)
```

## Expected behavior
I'm actually not sure how a nil value is represented in CSV but I think you just put nothing in between the two commas. In any case, this should at least throw an error instead of entering into an infinite loop.

## System (please complete the following information)
 - OS: macOS 10.15.4
 - CodableCSV: 0.5.1

**Comment by dehesa** [comment]
Hi @roydaw thank you for reporting and sorry for the inconvenience.. I will get to it right away.

> I'm actually not sure how a nil value is represented in CSV but I think you just put nothing in between the two commas. In any case, this should at least throw an error instead of entering into an infinite loop.

The encoding behavior of `nil` cases is controlled by the `nilStrategy` configuration value. By default is `.empty` which won't write anything. You can however pass a `.custom(...)` configuration value and write whatever you want.

**Comment by dehesa** [comment]
I have fixed the issue and added some tests to verify the behavior.

Thank you!
