### ISSUE TITLE
CSVEncoder.lazy<URL> should support an appending strategy

### ISSUE THREAD

**Issue by leisurehound** [dehesa/CodableCSV#21]
## Is your feature request related to a problem?
Sorry if this is available already, but couldn't find it in sources except in CSVWriter, but not CSVEncoder or in README.  

## Describe the solution you'd like
Simply, for a live time series serialization would want to append new data to the URL instead of overwrite it with a bufferingStrategy of sequential (but can also see where users wouldn't want it to append, so should be a separate strategy).

**Comment by dehesa** [comment]
Hi @leisurehound 

I am not sure I understand. Is the [`CSVEncoder.lazy(into:append:)`](https://github.com/dehesa/CodableCSV/blob/master/sources/declarative/encodable/Encoder.swift#L60) function already what you need?

**Comment by leisurehound** [comment]
Yes, it does.  Sorry for the noise.  Not sure why I couldn't find that as an optional parameter.

**Comment by dehesa** [comment]
No worries, @leisurehound.

Please notice that the appending functionality currently has some shortcomings (as stated in the [bugs project](https://github.com/dehesa/CodableCSV/projects/2)). It behaves as a "dumb" byte appender. That is:
- It doesn't perform any sanity check whether the file receiving the data has the same encoding as the one specified in the encoder settings.
- It doesn't check whether the passed headers matched the already-written file CSV headers row.
- It doesn't check whether the last written CSV row (before the file is opened) contain a row delimiter.

In general, you can overcome the current shortcomings fairly easily, but it is worth knowing. I haven't had time to improve the appending behavior yet.

**Comment by leisurehound** [comment]
Thanks Marcos.  

issue 1&2 are fine and if I'm writing differently to the same file I'd consider that my bug.  I am experiencing #3, even tho in deinit I endEncoding() on all encoders.  Its not a major issue as it only seems to occur when starting/stopping the app during the development iteration/cycle, but would be nice to prevent it.  Is there a better strategy?

**Comment by dehesa** [comment]
This should be something that the encoder manage for you. Alas, I haven't had time to improve the appending behavior, yet. Furthermore, I don't believe I will have time to work on it in the next 2 to 3 weeks. Sorry, I am pretty swamp now.

In the meantime, you can write a small file checker to validate whether the last character/s are a row delimiter. It shouldn't be a lot of work, but it is annoying to have to run that before a file is opened. Alternatively, you could learn how the library works and send a PR 😄 Although, in all honesty, that will probably take some time.

**Comment by leisurehound** [comment]
Thanks again Marcos.  Intuitively I would think encodeRow() would also write thee row delimiter but perhaps there are other reasons you don't do that.  I have however learned how to trap signals with Swift to ensure endEncoding() is called before abended shutdown. Yay!

**Comment by dehesa** [comment]
That is a good idea, @leisurehound.

Writing or not the row delimiter depends on the usage of Codable keyed and unkeyed container. Basically, Codable provides the user the freedom to write out-of-order with keyed containers, which forces the encoder to buffer data till it is sure the row is completed.

If you are using unkeyed containers everywhere and you  have set the buffering strategy to `.sequential`, the delimiter should be written (if it is not, it is probably a bug).
