### ISSUE TITLE
How to omit properties from the CSV file

### ISSUE THREAD

**Issue by babbage** [dehesa/CodableCSV#22]
## Question
How do I configure CodableCSV to omit selected properties from the object when creating the CSV file.

## Additional Context
Model objects contain fields that are Codable but which I do not wish to have included in the CSV file. I have not located a method in this package that enables me to do this, though perhaps it would simply omit any properties for which there was no matching label in the header row. (That would be a user friendly and simple way to provide this functionality if it does not exist.) 

## System
 - OS: macOS 10.15.5, Ubuntu somethingCurrent
 - CodableCSV: 0.6.1

**Comment by dehesa** [comment]
I am no sure I get what you mean. Could you provide a tiny example, please?

**Comment by babbage** [comment]
My object stores the result of a web form submission. It contains an ID property which is a UIID and the IP address of the submitter. I want to export the data in other properties as a CSV file, such as name,   department, email so it can be downloaded by an admin user. However, they do not want the UIIDs in their file (clutter) and should not get the IP address. 

Rather than having to create an intermediate object that does not contain these properties, I would like to be able to pass an array of my existing objects and just specify the properties of the object that should be left out of the CSV file.

**Comment by babbage** [comment]
My object stores the result of a web form submission. It contains an ID property which is a UUID and the IP address of the submitter. I want to export the data in other properties as a CSV file, such as name,   department, email so it can be downloaded by an admin user. However, they do not want the UUIDs in their file (clutter) and should not get the IP address. 

Rather than having to create an intermediate object that does not contain these properties, I would like to be able to pass an array of my existing objects and just specify the properties of the object that should be left out of the CSV file.

**Comment by dehesa** [comment]
Oh, I see. You have several ways to solve your problem. Let's suppose your web form submission is modeled as follows:
```swift
struct Submission: Encodable {
    let id: UUID
    let address: URL

    let name: String
    let department: String
    let email: String
}
```

The `id` and `address` are to be ignored by a Codable encoder and `name`, `department`, and `email` shall be encoded.
- Option 1: Provide a `CodingKeys` enum only specifying the exact property names you want to encode.
  ```swift
  extension Submission {
      private enum CodingKeys: Int, CodingKey {
          case name = 0
          case department = 1
          case email = 2
      }
  }
  ```

  Then use the encoder as usual.
  ```swift
  let submissions: [Submission] = [/* Array of submissions */]
  let encoder = CSVEncoder()
  let data = try encoder.encode(submissions, into: Data.self)
  ```

- Option 2: Define the `encode(to:)` function instead of relying on Codable's code generation.
  ```swift
  extension Submission {
      func encode(to encoder: Encoder) throws {
          var container = encoder.unkeyedContainer()
          try container.encode(self.name)
          try container.encode(self.department)
          try container.encode(self.email)
      }
  }
  ```

  Then use the encoder as usual.

- Option 3: Define the `encode(to:)` function and conditionally encode properties depending on the existence of `userInfo` keys.

  This is a bit more involved but let you have different encoding for different outputs. For example, you may want to encode _non-technical_ properties for managers and _technical_ properties for engineers.

Regards,
Marcos

**Comment by babbage** [comment]
Hi Marcos,
That's extremely helpful—and now you've written it would make a great addition to your readme file on the repo! :) 

I was previously looking for a point of customisation within CodableCSV—to define fields to pass over while writing the CSV file, without resorting to implementing your field-by-field write controls—rather than redefining the Codable process itself.

In this case, the data is previous webform submissions that are being accessed from a database, and other parts of the app rely on Codable as well, so redefining the encoding for the type is not an option. The third option you define would be possible, but now I understand this functionality isn't built natively into CodableCSV.

The application in question isn't dealing with large amounts of data at a time, so I think the most parsimonious approach is to simply map my existing objects to new structs that only contain the desired fields, and then pass those to Codable instead of the original model objects. Straightforward and doesn't risk side effects on Codable processing of these model objects in the future. Obviously that is incurring extra processing so would have some marginal performance cost but it's not going to be an issue for the current use case.

Thanks for your help. Most appreciated!
