### ISSUE TITLE
Make it conform to TopLevelDecoder/Encoder to use with Combine

### ISSUE THREAD

**Issue by marcblanchet** [dehesa/CodableCSV#25]
## Is your feature request related to a problem?
With the new Combine framework, one can chain the CSVDecoder.

## Describe the solution you'd like
conform to protocol TopLevelDecoder/Encoder

## Additional context
see examples from other Codable Frameworks such as XMLCoder and YAMS.

**Comment by dehesa** [comment]
Hi @marcblanchet,

I believe that is already implemented, you can find the `CSVDecoder` implementation of `TopLevelDecoder` [here](https://github.com/dehesa/CodableCSV/blob/master/sources/declarative/decodable/Decoder.swift#L103) and the `CSVEncoder` implementation to `TopLevelEncoder` [here](https://github.com/dehesa/CodableCSV/blob/master/sources/declarative/encodable/Encoder.swift#L101).

Is that not working for you?

**Comment by dehesa** [comment]
I am going to assume that that was what you needed and close this issue 😅 Feel free to reopen it, otherwise.
