### ISSUE TITLE
Encoding a single object produces a confusing error message.

### ISSUE THREAD

**Issue by GoldenJoe** [dehesa/CodableCSV#27]
When trying to encode a single object, the following error occurs:

```
struct Student: Encodable {
    let name: String, age: Int?, country: String?, hasPet: Bool?
}
let student = Student(name: "Marcos", age: 1, country: "Spain", hasPet: true)
let encoder = CSVEncoder { $0.headers = ["name", "age", "country", "hasPet"] }
let result = try encoder.encode(student, into: String.self)
print(result)

[CSVEncoder] Invalid coding path
	Reason: The coding key identifying a CSV row couldn't be transformed into an integer value.
	Help: The provided coding key identifying a CSV row must implement `intValue`.
	User info: Coding path: [CodingKeys(stringValue: "name", intValue: nil)], Key: CodingKeys(stringValue: "name", intValue: nil)
```

It works fine as long as the object is wrapped in an array, however. Browsing the source for a few minutes didn't make it clear to me why this is the case.

**Comment by dehesa** [comment]
Hi @GoldenJoe,

I am not sure to which level you drilled down in the code, so I will give you two explanations of why you are seeing that error:

- Higher level explanation.

  A CSV is semantically a list of rows. If the CSV is comprised of a single row, it is still a list of rows. The coding path let the framework figure out at which level to encode. A coding path of `[3]` is pointing to the third row within a CSV. A coding path of `[3, "hasPet"]` is pointing to the field `hasPet` within the third row.

  CodableCSV expects a keyed or unkeyed container at the very top of the coding path (i.e. when the coding path is an empty array `[]`). That container must be able to translate its coding keys into row index positions (only integer `RawRepresentable` enumerations are allowed).

- Lower level explanation.

  The `Student` structure definition is letting the compiler generate the `encode(to:)` function and `CodingKeys` enumeration. The code generated is similar to the following:

  ```swift
  extension Student {
      func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          container.encode(self.name, forKey: .name)
          container.encodeIfPresent(self.age, forKey: .age)
          container.encodeIfPresent(self.country, forKey: .country)
          container.encodeIfPresent(self.hasPet, forKey: .hasPet)
      }
      
      private enum CodingKeys: String, CodingKey {
          case name, age, country, hasPet
      }
  }
  ```

  Please notice that the `CodingKeys` structure is a `String` `RawRepresentable` enumeration. It doesn't return a row index (which for a CSV with a single row should be the index zero).

  A correct implementation will perform:

  ```swift
  var listContainer = encoder.unkeyedContainer()
  var rowContainer = listContainer.nestedContainer(keyedBy: CodingKeys.self)
  rowContainer.encode(self.name, forKey: .name)
  rowContainer.encodeIfPresent(self.age, forKey: .age)
  rowContainer.encodeIfPresent(self.country, forKey: .country)
  rowContainer.encodeIfPresent(self.hasPet, forKey: .hasPet)
  ```

  It is technically possible for the framework to create an edge case in which, if the first container cannot return a row index, then assume the CSV will only have a single row. However, some people write their own `encode(to:)` functions and they use `unkeyedContainers` for faster encoding (`UnkeyedContainer`s are slightly faster than `KeyedContainer`s).

**Comment by dehesa** [comment]
I am going to assume that that was what you needed and close this issue 😅 Feel free to reopen it, otherwise.
