### ISSUE TITLE
Lazy decoding a CSV with CRLF line endings fails without an error

### ISSUE THREAD

**Issue by xsleonard** [dehesa/CodableCSV#33]
## Describe the bug

Using using CSVDecoder.Lazy() on a CSV file with CRLF line endings, and the delimiter is not configured to be CRLF (the default is only `'\n'`), decoding rows will silently fail.

## To Reproduce
1. Create entity '...'
2. Perform action '....'

## Expected behavior

Either throw an error when an invalid row delimiter is encountered, or successfully parse both \n and \r\n line endings without additional configuration.

## System
 - OS: iOS 14.2
 - CodableCSV: 0.6.5

## Additional context

This is the call stack from lazy decoding down to where the internal error is thrown. In between, the error is eaten by a `try?` and the Lazy iterator terminates without error, despite not processing the CSV.

> #0  0x0000000102e0ba48 in CSVReader._parseEscapedField(rowIndex:escaping:) at CodableCSV/sources/imperative/reader/Reader.swift:278
#1	0x0000000102e091a0 in CSVReader._parseLine(rowIndex:) at CodableCSV/sources/imperative/reader/Reader.swift:165
#2	0x0000000102e0a1f8 in CSVReader.readRow() at CodableCSV/sources/imperative/reader/Reader.swift:112
#3	0x0000000102ddb160 in ShadowDecoder.Source.isRowAtEnd(index:) at CodableCSV/sources/declarative/decodable/internal/Source.swift:109
#4	0x0000000102dc1678 in CSVDecoder.Lazy.next() at CodableCSV/sources/declarative/decodable/DecoderLazy.swift:48

**Comment by dehesa** [comment]
Hey @xsleonard,

Thanks for reaching out. I am not in front of the computer screen right now. I'll try it out once I'm back home. However, I'm not exactly sure I understand what the problem is. Which one of the following is the problem?
1. The default line ending is `\n`, but you expect it to be `\r\n`?
2. You expects both `\n` and `\r\n` to be recognized as line ends by default?
3. The default behaviour works as expected with the regular decoder but not with the lazy decoder?
3. Something else.

Regards,
Marcos

**Comment by dehesa** [comment]
Alright, I've been re-reading what you wrote and building some sample code.

Delimiters (whether field or row) are currently only implemented as single `String` values (actually `UnicodeScalasView`s). This means, there are currently no way to support multiple row delimiters (such `\r\n` and `\n`). I see the value of that and implementing it is not a lot of effort; however there is a small performance cost to be payed for adding this feature. In any case, I have added the feature to the roadmap [here](https://github.com/dehesa/CodableCSV/projects/1).

You can currently parse files where sometimes the row delimiter is a LF and other times CRLF by using the `trimStrategy` configuration value:
```swift
config.headerStrategy = .firstLine
config.delimiters.field = ","  // This is the default
config.delimiters.row = "\n"  // This is the default
config.trimStrategy = ["\r"]
```
The big problem with the trim strategy configuration value is that is implemented as `Foundation`'s `CharacterSet`, which is an ObjC object on Apple systems (not on Linux). This mean you will probably experience a noticeable drop in performance.

I hope I have correctly understand what you were trying to convey.

**Comment by xsleonard** [comment]
Yes, thank you.
