### ISSUE TITLE
Extra comma in header or data line causes failure to parse subsequent lines

### ISSUE THREAD

**Issue by DressTheMonkey** [dehesa/CodableCSV#34]
## Describe the bug
Having an extra comma in a data line (which is usually caused by the CSV creator failing to quote a field) causes that line and all subsequent lines to fail to parse.  Having an extra comma at the end of the header line causes all subsequent data lines to fail to parse.

## To Reproduce

Please see the attached test file (it is really a .swift file, but I changed the extension to .txt in order to attach it).
[DecodingBadInputTests.txt](https://github.com/dehesa/CodableCSV/files/6134480/DecodingBadInputTests.txt)

## Expected behavior
Both of these situations (additional commas in either header or data line) are forbidden by rfc4180, so I would expect an exception to be raised.

## System
 - OS: macOS 11.2.3
 - CodableCSV: 0.6.2

## Additional context
I encountered both of these instances of ill-formed CSV in files I downloaded from my banks.  I'm using CodableCSV in a Swift app I've written to take the differently formatted CSV from each bank and create a standard format which I then import into a spreadsheet for further analysis.

**Comment by dehesa** [comment]
Hi @DressTheMonkey,

Indeed, there seems to be an issue there. I will try to see what the problem is, but thank you for the tests. They are very helpful to replicate the problem.

**Comment by dehesa** [comment]
Hey @DressTheMonkey. I fixed the issue and added your tests in the test suite. The changes are in `develop` and as soon as you can check them out and give me the "thumbs up", I will merge to master and make a minor release.

I would appreciate if you can test it out with your data.

**Comment by DressTheMonkey** [comment]
That definitely does catch and report those two problems I was having.  That's brilliant.

However, it will have to be up to you if it is a thumbs up or not, because this has actually introduced a minor problem!  One of my files ends with a line followed by a new line.  This is now reported as an error:

[CSVReader] Invalid input
	Reason: The number of fields is not constant between rows.
	Help: Make sure the CSV file has always the same amount of fields per row (including the header row).
	User info: Row index: 369, Number of expected fields: 6, Number of parsed fields: 1

Now, according to my old friend rfc4180, (in: 2. Definition of the CSV format):
The last record in the file may or may not have an ending line
       break.

So, IMHO, this should be allowed. What do you think?

**Comment by dehesa** [comment]
That should definitely be allowed since it is not only in the RFC, but it is also very common. I will try to figure out how to "add back" that functionality. Fixing your bug had the side-effect of making the library more strict.

Good catch, anyways. This problem highlights the need for more tests.

**Comment by dehesa** [comment]
Alright @DressTheMonkey I have added the functionality to ignore empty rows and I've added a test to verify the behavior. Could you please check it out with your data again? If it works well and you have no further requirements :) I will make a new minor release.

**Comment by DressTheMonkey** [comment]
👍That has fixed it.  New tests are looking good.  That really meets and exceeds all my requirements :), so I'm going to close this.  Thanks so much for the great code and the swift updates.

**Comment by MaxDesiatov** [comment]
Would it be possible to make this configurable? I don't want such error to be thrown as there's no way to pre-process a given CSV before parsing. What would be the best way to parse CSVs that don't always have the same amount of fields per row with this library?

**Comment by dehesa** [comment]
Hey @MaxDesiatov,
That could definitely be configurable. But in all honesty I am not sure when I can add such functionality, sorry. I will add it to the roadmap, though.
