### ISSUE TITLE
trimStrategy does not trim characters inside of a quoted field

### ISSUE THREAD

**Issue by xsleonard** [dehesa/CodableCSV#36]
## Describe the bug

trimStrategy characters are not trimmed from a quoted string field.

## To Reproduce

Use a CSVDecoder with `trimStrategy = .whitespaces` and a CSV like:

```
Name,Value
" Foo ","1"
```

The Name field is parsed as " Foo " - spaces are not trimmed from the string.

## Expected behavior

Characters in trimStrategy trimmed from the result

## System
 - CodableCSV: 0.6.6

**Comment by dehesa** [comment]
Hey @xsleonard, anything that is within quotes is considered "sacred"; Meaning that the `trimStrategy` doesn't affect its content. Therefore the library is working as expected. This way of working is specified in the [RFCT4180](https://tools.ietf.org/html/rfc4180) and follow other type of decoding libraries with similar escaping capabilities.

**Comment by xsleonard** [comment]
OK thanks
