### ISSUE TITLE
Can't`pod install` for macOS 10.15

### ISSUE THREAD

**Issue by eppz** [dehesa/CodableCSV#5]
It is just that.

CocoaPods says:
```
[!] The platform of the target `<TARGET_NAME>` (macOS 10.15) is not compatible with `CodableCSV (0.4.0)`, which does not support `macOS`.
```

Is there any specific reason for that?
Could you perhaps update the podspec?

**Comment by dehesa** [comment]
Hi @eppz,

Thank you for bringing the issue to me. I am not a CocoaPods user, though (this was a contribution from @davbeck). Feel free to send a pull request changing whatever is wrong with the podspec. Skimming the [CocoaPods documentation](https://guides.cocoapods.org/syntax/podspec.html#deployment_target), I have failed to figure out what is wrong.
